### ISSUE TITLE
The `instance` attributes get updated before `serializer.update` called

### ISSUE THREAD

**Issue by jeffryadityatama** [senseobservationsystems/drf-model-serializer#5]
The [`validate`](https://github.com/senseobservationsystems/drf-model-serializer/blob/1ccb0eeab6c2754aa911fff20ba7571e3f549800/drf_model_serializer/serializers.py#L10-L12) method already update the `self.instance` attributes with the new data before the [`update`](https://github.com/encode/django-rest-framework/blob/c5d9144aef1144825942ddffe0a6af23102ef44a/rest_framework/serializers.py#L968-L992) method called. This should be avoided. The `validate` should only perform validation, no more than that.

**Comment by panjiyudasetya** [comment]
Addressed in #6
